version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: ecommerce-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  mongo-data:
